name: subliminal-subtitles
summary: Subtitles, faster than your thoughts
description: |
  Find and download subtitles from most popular subtitle providers, for entire collection or just one video.

      subliminal-subtitles download --language en movie.mp4

  For integration with other apps and scripts make an alias to original name.

      snap alias subliminal-subtitles subliminal
      subliminal --help

adopt-info: version
base: core18
grade: stable
confinement: strict

apps:
  subliminal-subtitles:
    command: bin/subliminal
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    plugs:
      - home
      - removable-media
      - network

parts:
  version:
    plugin: nil
    override-build: |
      snapcraftctl set-version `curl --silent \
      https://api.github.com/repos/diaoul/subliminal/releases/latest \
      | jq --raw-output .tag_name`
    build-packages: [curl, jq]

  subliminal:
    after: [version]
    source: https://github.com/diaoul/subliminal.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    source-depth: 1
    plugin: python
